services:
  - type: web
    name: etfdportal
    runtime: node
    buildCommand: npm install && npm run build
    publishDir: dist
    disk:
      name: node_modules_cache
      mountPath: /opt/render/project/src/node_modules
      sizeGB: 1